controller:
  replicaCount: 1

lvmd:
  socketName: /tmp/topolvm/daemonset_lvmd/lvmd.sock
  deviceClasses:
    - name: "ssd"
      volume-group: "node-myvg1"
      default: true
      spare-gb: 1
    - name: "hdd1"
      volume-group: "node-myvg2"
      spare-gb: 1
    - name: "hdd2"
      volume-group: "node-myvg3"
      spare-gb: 1
  volumes:
    - name: lvmd-socket-dir
      hostPath:
        path: /tmp/topolvm/daemonset_lvmd
        type: DirectoryOrCreate
  volumeMounts:
    - name: lvmd-socket-dir
      mountPath: /tmp/topolvm/daemonset_lvmd

node:
  volumes:
    - name: registration-dir
      hostPath:
        path: /var/lib/kubelet/plugins_registry/
        type: Directory
    - name: node-plugin-dir
      hostPath:
        path: /var/lib/kubelet/plugins/topolvm.io/node
        type: DirectoryOrCreate
    - name: csi-plugin-dir
      hostPath:
        path: /var/lib/kubelet/plugins/kubernetes.io/csi
        type: DirectoryOrCreate
    - name: pod-volumes-dir
      hostPath:
        path: /var/lib/kubelet/pods/
        type: DirectoryOrCreate
    - name: lvmd-socket-dir
      hostPath:
        path: /tmp/topolvm/daemonset_lvmd
        type: Directory

podSecurityPolicy:
  create: false

cert-manager:
  enabled: true
